DROP TABLE IF EXISTS SYS_DEPT;

CREATE TABLE SYS_DEPT
(
    ID               VARCHAR(32) NOT NULL COMMENT 'ID',
    PARENT_ID        VARCHAR(32) COMMENT '父部门ID',
    DEPT_CODE        VARCHAR(64) COMMENT '部门编码',
    DEPT_NAME        VARCHAR(128) COMMENT '部门名称',
    LEADER_USER_ID   VARCHAR(32) COMMENT '部门负责人ID',
    LEADER_USER_NAME VARCHAR(128) COMMENT '部门负责人名称',
    DEPT_SORT        INT COMMENT '显示顺序',
    PHONE            VARCHAR(255) COMMENT '联系电话',
    EMAIL            VARCHAR(255) COMMENT '联系邮箱',
    STATUS           INT COMMENT '数据状态（0正常 1停用）',
    DELETED          INT COMMENT '是否删除（0正常 1删除）',
    REVISION         VARCHAR(32) COMMENT '乐观锁',
    TENANT_ID        VARCHAR(32) COMMENT '租户号',
    CREATED_BY       VARCHAR(32) COMMENT '创建人',
    CREATED_AT       DATETIME COMMENT '创建时间',
    UPDATED_BY       VARCHAR(32) COMMENT '更新人',
    UPDATED_AT       DATETIME COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '部门表';

DROP TABLE IF EXISTS SYS_DICT_TYPE;

CREATE TABLE SYS_DICT_TYPE
(
    ID          VARCHAR(32) NOT NULL COMMENT 'ID',
    DICT_CODE   VARCHAR(64) COMMENT '字典编码',
    DICT_NAME   VARCHAR(128) COMMENT '字典名称',
    DICT_TYPE   INT COMMENT '字典类型（0字符串 1数字）',
    DICT_REMARK VARCHAR(255) COMMENT '字典描述',
    STATUS      INT COMMENT '数据状态（0正常 1停用）',
    DELETED     INT COMMENT '是否删除（0正常 1删除）',
    REVISION    VARCHAR(32) COMMENT '乐观锁',
    TENANT_ID   VARCHAR(32) COMMENT '租户号',
    CREATED_BY  VARCHAR(32) COMMENT '创建人',
    CREATED_AT  DATETIME COMMENT '创建时间',
    UPDATED_BY  VARCHAR(32) COMMENT '更新人',
    UPDATED_AT  DATETIME COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '字典类型表';

DROP TABLE IF EXISTS SYS_DICT_ITEM;

CREATE TABLE SYS_DICT_ITEM
(
    ID          VARCHAR(32) NOT NULL COMMENT 'ID',
    DICT_CODE   VARCHAR(64) COMMENT '字典编码',
    ITEM_VALUE  VARCHAR(255) COMMENT '字典项值',
    ITEM_LABEL  VARCHAR(255) COMMENT '字典项标签',
    ITEM_REMARK VARCHAR(255) COMMENT '字典项描述',
    ITEM_SORT   INT COMMENT '字典项排序',
    ITEM_STYLE  VARCHAR(255) COMMENT '字典项样式',
    ITEM_CSS    TEXT COMMENT '字典项CSS',
    STATUS      INT COMMENT '数据状态（0正常 1停用）',
    DELETED     INT COMMENT '是否删除（0正常 1删除）',
    REVISION    VARCHAR(32) COMMENT '乐观锁',
    TENANT_ID   VARCHAR(32) COMMENT '租户号',
    CREATED_BY  VARCHAR(32) COMMENT '创建人',
    CREATED_AT  DATETIME COMMENT '创建时间',
    UPDATED_BY  VARCHAR(32) COMMENT '更新人',
    UPDATED_AT  DATETIME COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '字典数据表';

DROP TABLE IF EXISTS SYS_ERROR_CODE;

CREATE TABLE SYS_ERROR_CODE
(
    ID               VARCHAR(32) NOT NULL COMMENT 'ID',
    APPLICATION_ID   VARCHAR(255) COMMENT '应用ID',
    APPLICATION_NAME VARCHAR(128) COMMENT '应用名称',
    ERROR_TYPE       VARCHAR(255) COMMENT '错误码类型',
    ERROR_CODE       VARCHAR(255) COMMENT '错误码编码',
    ERROR_MESSAGE    VARCHAR(255) COMMENT '错误码提示',
    ERROR_REMARK     VARCHAR(255) COMMENT '错误码描述',
    STATUS           INT COMMENT '数据状态（0正常 1停用）',
    DELETED          INT COMMENT '是否删除（0正常 1删除）',
    REVISION         VARCHAR(32) COMMENT '乐观锁',
    TENANT_ID        VARCHAR(32) COMMENT '租户号',
    CREATED_BY       VARCHAR(32) COMMENT '创建人',
    CREATED_AT       DATETIME COMMENT '创建时间',
    UPDATED_BY       VARCHAR(32) COMMENT '更新人',
    UPDATED_AT       DATETIME COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '错误码表';

DROP TABLE IF EXISTS SYS_LOGIN_LOG;

CREATE TABLE SYS_LOGIN_LOG
(
    ID           VARCHAR(32) NOT NULL COMMENT 'ID',
    TRACE_ID     VARCHAR(255) COMMENT '链路追踪编号',
    USER_ID      VARCHAR(255) COMMENT '用户编号',
    USER_TYPE    VARCHAR(255) COMMENT '用户类型',
    USER_NAME    VARCHAR(128) COMMENT '用户名称',
    USER_IP      VARCHAR(255) COMMENT '用户 IP',
    USER_AGENT   VARCHAR(255) COMMENT '浏览器 UA',
    LOGIN_RESULT VARCHAR(255) COMMENT '登陆结果',
    LOG_TYPE     VARCHAR(255) COMMENT '日志类型',
    LOG_REQUEST  TEXT COMMENT '请求日志',
    LOG_RESPONSE TEXT COMMENT '响应日志',
    STATUS       INT COMMENT '数据状态（0正常 1停用）',
    DELETED      INT COMMENT '是否删除（0正常 1删除）',
    REVISION     VARCHAR(32) COMMENT '乐观锁',
    TENANT_ID    VARCHAR(32) COMMENT '租户号',
    CREATED_BY   VARCHAR(32) COMMENT '创建人',
    CREATED_AT   DATETIME COMMENT '创建时间',
    UPDATED_BY   VARCHAR(32) COMMENT '更新人',
    UPDATED_AT   DATETIME COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '系统登录日志';

DROP TABLE IF EXISTS SYS_MENU;

CREATE TABLE SYS_MENU
(
    ID              VARCHAR(32) NOT NULL COMMENT 'ID',
    PARENT_ID       VARCHAR(255) COMMENT '父菜单ID',
    MENU_CODE       VARCHAR(64) COMMENT '菜单编码',
    MENU_NAME       VARCHAR(128) COMMENT '菜单名称',
    MENU_TYPE       VARCHAR(255) COMMENT '菜单类型',
    MENU_PATH       VARCHAR(255) COMMENT '路由地址',
    MENU_ICON       VARCHAR(255) COMMENT '菜单图标',
    MENU_COMPONENT  VARCHAR(255) COMMENT '组件路径',
    MENU_SORT       INT COMMENT '显示顺序',
    MENU_PERMISSION VARCHAR(255) COMMENT '权限标识',
    KEEP_ALIVE      INT COMMENT '是否缓存（0不缓存 1缓存）',
    VISIBLE         INT COMMENT '是否可见（0正常 1隐藏）',
    STATUS          INT COMMENT '数据状态（0正常 1停用）',
    DELETED         INT COMMENT '是否删除（0正常 1删除）',
    REVISION        VARCHAR(32) COMMENT '乐观锁',
    TENANT_ID       VARCHAR(32) COMMENT '租户号',
    CREATED_BY      VARCHAR(32) COMMENT '创建人',
    CREATED_AT      DATETIME COMMENT '创建时间',
    UPDATED_BY      VARCHAR(32) COMMENT '更新人',
    UPDATED_AT      DATETIME COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '菜单表';

DROP TABLE IF EXISTS SYS_OPERATE_LOG;

CREATE TABLE SYS_OPERATE_LOG
(
    ID              VARCHAR(32) NOT NULL COMMENT 'ID',
    TRACE_ID        VARCHAR(32) COMMENT '链路追踪ID',
    USER_ID         VARCHAR(32) COMMENT '用户ID',
    USER_TYPE       VARCHAR(255) COMMENT '用户类型',
    USER_IP         VARCHAR(255) COMMENT '用户 IP',
    USER_AGENT      VARCHAR(255) COMMENT '浏览器 UA',
    SYSTEM_MODULE   VARCHAR(255) COMMENT '系统模块',
    OPERATE_NAME    VARCHAR(128) COMMENT '操作名称',
    OPERATE_TYPE    VARCHAR(255) COMMENT '操作分类',
    OPERATE_CONTENT VARCHAR(255) COMMENT '操作内容',
    OPERATE_AT      DATETIME COMMENT '操作时间',
    COST_TIME       VARCHAR(255) COMMENT '请求耗时',
    OPERATE_EXTS    VARCHAR(255) COMMENT '拓展字段',
    REQUEST_METHOD  VARCHAR(255) COMMENT '请求方法名',
    REQUEST_URL     VARCHAR(255) COMMENT '请求地址',
    REQUEST_BODY    TEXT COMMENT '请求入参',
    RESPONSE_CODE   VARCHAR(255) COMMENT '响应状态码',
    RESPONSE_MSG    VARCHAR(255) COMMENT '响应提示语',
    RESPONSE_DATA   TEXT COMMENT '响应出参',
    STATUS          INT COMMENT '数据状态（0正常 1停用）',
    DELETED         INT COMMENT '是否删除（0正常 1删除）',
    REVISION        VARCHAR(32) COMMENT '乐观锁',
    TENANT_ID       VARCHAR(32) COMMENT '租户号',
    CREATED_BY      VARCHAR(32) COMMENT '创建人',
    CREATED_AT      DATETIME COMMENT '创建时间',
    UPDATED_BY      VARCHAR(32) COMMENT '更新人',
    UPDATED_AT      DATETIME COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '操作日志记录表';

DROP TABLE IF EXISTS SYS_POST;

CREATE TABLE SYS_POST
(
    ID          VARCHAR(32) NOT NULL COMMENT 'ID',
    POST_CODE   VARCHAR(64) COMMENT '岗位编码',
    POST_NAME   VARCHAR(128) COMMENT '岗位名称',
    POST_REMARK VARCHAR(255) COMMENT '岗位描述',
    POST_SORT   INT COMMENT '显示顺序',
    STATUS      INT COMMENT '数据状态（0正常 1停用）',
    DELETED     INT COMMENT '是否删除（0正常 1删除）',
    REVISION    VARCHAR(32) COMMENT '乐观锁',
    TENANT_ID   VARCHAR(32) COMMENT '租户号',
    CREATED_BY  VARCHAR(32) COMMENT '创建人',
    CREATED_AT  DATETIME COMMENT '创建时间',
    UPDATED_BY  VARCHAR(32) COMMENT '更新人',
    UPDATED_AT  DATETIME COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '岗位表';

DROP TABLE IF EXISTS SYS_ROLE;

CREATE TABLE SYS_ROLE
(
    ID          VARCHAR(32) NOT NULL COMMENT 'ID',
    ROLE_CODE   VARCHAR(64) COMMENT '角色代码',
    ROLE_NAME   VARCHAR(128) COMMENT '角色名称',
    ROLE_REMARK VARCHAR(255) COMMENT '角色描述',
    ROLE_TYPE   VARCHAR(255) COMMENT '角色类型',
    ROLE_SORT   INT COMMENT '显示顺序',
    ROLE_SCOPE  INT COMMENT '数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）',
    STATUS      INT COMMENT '数据状态（0正常 1停用）',
    DELETED     INT COMMENT '是否删除（0正常 1删除）',
    REVISION    VARCHAR(32) COMMENT '乐观锁',
    TENANT_ID   VARCHAR(32) COMMENT '租户号',
    CREATED_BY  VARCHAR(32) COMMENT '创建人',
    CREATED_AT  DATETIME COMMENT '创建时间',
    UPDATED_BY  VARCHAR(32) COMMENT '更新人',
    UPDATED_AT  DATETIME COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '角色表';

DROP TABLE IF EXISTS SYS_ROLE_MENU;

CREATE TABLE SYS_ROLE_MENU
(
    ID         VARCHAR(32) NOT NULL COMMENT 'ID',
    ROLE_ID    VARCHAR(255) COMMENT '角色ID',
    MENU_ID    VARCHAR(255) COMMENT '菜单ID',
    STATUS     INT COMMENT '数据状态（0正常 1停用）',
    DELETED    INT COMMENT '是否删除（0正常 1删除）',
    REVISION   VARCHAR(32) COMMENT '乐观锁',
    TENANT_ID  VARCHAR(32) COMMENT '租户号',
    CREATED_BY VARCHAR(32) COMMENT '创建人',
    CREATED_AT DATETIME COMMENT '创建时间',
    UPDATED_BY VARCHAR(32) COMMENT '更新人',
    UPDATED_AT DATETIME COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '角色菜单中间表';

DROP TABLE IF EXISTS SYS_USER_ROLE;

CREATE TABLE SYS_USER_ROLE
(
    ID         VARCHAR(32) NOT NULL COMMENT 'ID',
    USER_ID    VARCHAR(255) COMMENT '用户ID',
    ROLE_ID    VARCHAR(255) COMMENT '角色ID',
    STATUS     INT COMMENT '数据状态（0正常 1停用）',
    DELETED    INT COMMENT '是否删除（0正常 1删除）',
    REVISION   VARCHAR(32) COMMENT '乐观锁',
    TENANT_ID  VARCHAR(32) COMMENT '租户号',
    CREATED_BY VARCHAR(32) COMMENT '创建人',
    CREATED_AT DATETIME COMMENT '创建时间',
    UPDATED_BY VARCHAR(32) COMMENT '更新人',
    UPDATED_AT DATETIME COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '用户角色中间表';

DROP TABLE IF EXISTS SYS_SENSITIVE_WORD;

CREATE TABLE SYS_SENSITIVE_WORD
(
    ID          VARCHAR(32) NOT NULL COMMENT 'ID',
    WORD_NAME   VARCHAR(255) COMMENT '敏感词',
    WORD_TAGS   VARCHAR(255) COMMENT '敏感词标签',
    WORD_REMARK VARCHAR(255) COMMENT '敏感词描述',
    STATUS      INT COMMENT '数据状态（0正常 1停用）',
    DELETED     INT COMMENT '是否删除（0正常 1删除）',
    REVISION    VARCHAR(32) COMMENT '乐观锁',
    TENANT_ID   VARCHAR(32) COMMENT '租户号',
    CREATED_BY  VARCHAR(32) COMMENT '创建人',
    CREATED_AT  DATETIME COMMENT '创建时间',
    UPDATED_BY  VARCHAR(32) COMMENT '更新人',
    UPDATED_AT  DATETIME COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '系统敏感词表';

DROP TABLE IF EXISTS SYS_SOCIAL_USER;

CREATE TABLE SYS_SOCIAL_USER
(
    ID             VARCHAR(32) NOT NULL COMMENT 'ID',
    SOCIAL_TYPE    INT COMMENT '社交平台的类型',
    SOCIAL_OPEN_ID VARCHAR(255) COMMENT '社交 openid',
    SOCIAL_TOKEN   VARCHAR(255) COMMENT '社交 token',
    RAW_TOKEN_INFO VARCHAR(255) COMMENT '原始 Token 数据，一般是 JSON 格式',
    RAW_USER_INFO  VARCHAR(255) COMMENT '原始用户数据，一般是 JSON 格式',
    NICK_NAME      VARCHAR(128) COMMENT '用户昵称',
    USER_AVATAR    VARCHAR(255) COMMENT '用户头像',
    SOCIAL_CODE    VARCHAR(255) COMMENT '最后一次的认证 code',
    SOCIAL_STATE   VARCHAR(255) COMMENT '最后一次的认证 state',
    STATUS         INT COMMENT '数据状态（0正常 1停用）',
    DELETED        INT COMMENT '是否删除（0正常 1删除）',
    REVISION       VARCHAR(32) COMMENT '乐观锁',
    TENANT_ID      VARCHAR(32) COMMENT '租户号',
    CREATED_BY     VARCHAR(32) COMMENT '创建人',
    CREATED_AT     DATETIME COMMENT '创建时间',
    UPDATED_BY     VARCHAR(32) COMMENT '更新人',
    UPDATED_AT     DATETIME COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '社交用户表';

DROP TABLE IF EXISTS SYS_SOCIAL_USER_BIND;

CREATE TABLE SYS_SOCIAL_USER_BIND
(
    ID             VARCHAR(32) NOT NULL COMMENT 'ID',
    USER_ID        VARCHAR(255) COMMENT '系统用户ID',
    USER_TYPE      VARCHAR(255) COMMENT '用户类型',
    SOCIAL_USER_ID VARCHAR(255) COMMENT '社交用户ID',
    SOCIAL_TYPE    VARCHAR(255) COMMENT '社交平台的类型',
    STATUS         INT COMMENT '数据状态（0正常 1停用）',
    DELETED        INT COMMENT '是否删除（0正常 1删除）',
    REVISION       VARCHAR(32) COMMENT '乐观锁',
    TENANT_ID      VARCHAR(32) COMMENT '租户号',
    CREATED_BY     VARCHAR(32) COMMENT '创建人',
    CREATED_AT     DATETIME COMMENT '创建时间',
    UPDATED_BY     VARCHAR(32) COMMENT '更新人',
    UPDATED_AT     DATETIME COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '社交用户绑定表';

DROP TABLE IF EXISTS SYS_TENANT;

CREATE TABLE SYS_TENANT
(
    ID              VARCHAR(32) NOT NULL COMMENT 'ID',
    TENANT_CODE     VARCHAR(64) COMMENT '租户编码',
    TENANT_NAME     VARCHAR(128) COMMENT '租户名',
    CONTACT_USER_ID VARCHAR(255) COMMENT '联系人的用户ID',
    CONTACT_NAME    VARCHAR(128) COMMENT '联系人',
    CONTACT_PHONE   VARCHAR(255) COMMENT '联系手机',
    TENANT_DOMAIN   VARCHAR(255) COMMENT '绑定域名',
    PACKAGE_ID      VARCHAR(255) COMMENT '租户套餐编号',
    EXPIRE_AT       VARCHAR(255) COMMENT '过期时间',
    ACCOUNT_COUNT   VARCHAR(255) COMMENT '账号数量',
    STATUS          INT COMMENT '数据状态（0正常 1停用）',
    DELETED         INT COMMENT '是否删除（0正常 1删除）',
    REVISION        VARCHAR(32) COMMENT '乐观锁',
    TENANT_ID       VARCHAR(32) COMMENT '租户号',
    CREATED_BY      VARCHAR(32) COMMENT '创建人',
    CREATED_AT      DATETIME COMMENT '创建时间',
    UPDATED_BY      VARCHAR(32) COMMENT '更新人',
    UPDATED_AT      DATETIME COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '租户表';

DROP TABLE IF EXISTS SYS_PACKAGE;

CREATE TABLE SYS_PACKAGE
(
    ID             VARCHAR(32) NOT NULL COMMENT 'ID',
    PACKAGE_CODE   VARCHAR(64) COMMENT '套餐代码',
    PACKAGE_NAME   VARCHAR(128) COMMENT '套餐名称',
    PACKAGE_REMARK VARCHAR(255) COMMENT '套餐描述',
    PACKAGE_EXES   DECIMAL(24, 6) COMMENT '套餐费用',
    STATUS         INT COMMENT '数据状态（0正常 1停用）',
    DELETED        INT COMMENT '是否删除（0正常 1删除）',
    REVISION       VARCHAR(32) COMMENT '乐观锁',
    TENANT_ID      VARCHAR(32) COMMENT '租户号',
    CREATED_BY     VARCHAR(32) COMMENT '创建人',
    CREATED_AT     DATETIME COMMENT '创建时间',
    UPDATED_BY     VARCHAR(32) COMMENT '更新人',
    UPDATED_AT     DATETIME COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '套餐表';

DROP TABLE IF EXISTS SYS_USER_POST;

CREATE TABLE SYS_USER_POST
(
    ID         VARCHAR(32) NOT NULL COMMENT 'ID',
    USER_ID    VARCHAR(32) COMMENT '用户ID',
    POST_ID    VARCHAR(32) COMMENT '岗位ID',
    STATUS     INT COMMENT '数据状态（0正常 1停用）',
    DELETED    INT COMMENT '是否删除（0正常 1删除）',
    REVISION   VARCHAR(32) COMMENT '乐观锁',
    TENANT_ID  VARCHAR(32) COMMENT '租户号',
    CREATED_BY VARCHAR(32) COMMENT '创建人',
    CREATED_AT DATETIME COMMENT '创建时间',
    UPDATED_BY VARCHAR(32) COMMENT '更新人',
    UPDATED_AT DATETIME COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '用户岗位表';

DROP TABLE IF EXISTS SYS_USERS;

CREATE TABLE SYS_USERS
(
    ID          VARCHAR(32) NOT NULL COMMENT 'ID',
    USER_CODE   VARCHAR(64) COMMENT '用户编码',
    USER_NAME   VARCHAR(128) COMMENT '用户名称',
    NICK_NAME   VARCHAR(128) COMMENT '用户昵称',
    USER_REMARK VARCHAR(255) COMMENT '用户描述',
    PASSWORD    VARCHAR(255) COMMENT '登录密码',
    EMAIL       VARCHAR(255) COMMENT '用户邮箱',
    PHONE       VARCHAR(255) COMMENT '手机号码',
    SEX         INT COMMENT '用户性别（0女性 1男性）',
    AVATAR      VARCHAR(255) COMMENT '头像地址',
    LOGIN_IP    VARCHAR(255) COMMENT '最后登录IP',
    LOGIN_DATE  DATETIME COMMENT '最后登录时间',
    STATUS      INT COMMENT '数据状态（0正常 1停用）',
    DELETED     INT COMMENT '是否删除（0正常 1删除）',
    REVISION    VARCHAR(32) COMMENT '乐观锁',
    TENANT_ID   VARCHAR(32) COMMENT '租户号',
    CREATED_BY  VARCHAR(128) COMMENT '创建人',
    CREATED_AT  DATETIME COMMENT '创建时间',
    UPDATED_BY  VARCHAR(128) COMMENT '更新人',
    UPDATED_AT  DATETIME COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '用户表';

DROP TABLE IF EXISTS SYS_COMPANY;

CREATE TABLE SYS_COMPANY
(
    ID               VARCHAR(32) NOT NULL COMMENT 'ID',
    PARENT_ID        VARCHAR(32) COMMENT '父公司ID',
    COMPANY_CODE     VARCHAR(64) COMMENT '公司编码',
    COMPANY_NAME     VARCHAR(128) COMMENT '公司名称',
    LEADER_USER_ID   VARCHAR(32) COMMENT '公司负责人ID',
    LEADER_USER_NAME VARCHAR(128) COMMENT '公司负责人名称',
    COMPANY_SORT     INT COMMENT '显示顺序',
    PHONE            VARCHAR(255) COMMENT '联系电话',
    EMAIL            VARCHAR(255) COMMENT '联系邮箱',
    STATUS           INT COMMENT '数据状态（0正常 1停用）',
    DELETED          INT COMMENT '是否删除（0正常 1删除）',
    REVISION         VARCHAR(32) COMMENT '乐观锁',
    TENANT_ID        VARCHAR(32) COMMENT '租户号',
    CREATED_BY       VARCHAR(32) COMMENT '创建人',
    CREATED_AT       DATETIME COMMENT '创建时间',
    UPDATED_BY       VARCHAR(32) COMMENT '更新人',
    UPDATED_AT       DATETIME COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '公司表';

DROP TABLE IF EXISTS SYS_COMPANY_DEPT;

CREATE TABLE SYS_COMPANY_DEPT
(
    ID         VARCHAR(32) NOT NULL COMMENT 'ID',
    COMPANY_ID VARCHAR(32) COMMENT '公司ID',
    DEPT_ID    VARCHAR(32) COMMENT '部门ID',
    STATUS     INT COMMENT '数据状态（0正常 1停用）',
    DELETED    INT COMMENT '是否删除（0正常 1删除）',
    REVISION   VARCHAR(32) COMMENT '乐观锁',
    TENANT_ID  VARCHAR(32) COMMENT '租户号',
    CREATED_BY VARCHAR(32) COMMENT '创建人',
    CREATED_AT DATETIME COMMENT '创建时间',
    UPDATED_BY VARCHAR(32) COMMENT '更新人',
    UPDATED_AT DATETIME COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '公司部门表';

DROP TABLE IF EXISTS SYS_COMPANY_POST;

CREATE TABLE SYS_COMPANY_POST
(
    ID         VARCHAR(32) NOT NULL COMMENT 'ID',
    COMPANY_ID VARCHAR(32) COMMENT '公司ID',
    POST_ID    VARCHAR(32) COMMENT '岗位ID',
    STATUS     INT COMMENT '数据状态（0正常 1停用）',
    DELETED    INT COMMENT '是否删除（0正常 1删除）',
    REVISION   VARCHAR(32) COMMENT '乐观锁',
    TENANT_ID  VARCHAR(32) COMMENT '租户号',
    CREATED_BY VARCHAR(32) COMMENT '创建人',
    CREATED_AT DATETIME COMMENT '创建时间',
    UPDATED_BY VARCHAR(32) COMMENT '更新人',
    UPDATED_AT DATETIME COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '公司岗位表';

DROP TABLE IF EXISTS SYS_DEPT_POST;

CREATE TABLE SYS_DEPT_POST
(
    ID         VARCHAR(32) NOT NULL COMMENT 'ID',
    DEPT_ID    VARCHAR(32) COMMENT '部门ID',
    POST_ID    VARCHAR(32) COMMENT '岗位ID',
    STATUS     INT COMMENT '数据状态（0正常 1停用）',
    DELETED    INT COMMENT '是否删除（0正常 1删除）',
    REVISION   VARCHAR(32) COMMENT '乐观锁',
    TENANT_ID  VARCHAR(32) COMMENT '租户号',
    CREATED_BY VARCHAR(32) COMMENT '创建人',
    CREATED_AT DATETIME COMMENT '创建时间',
    UPDATED_BY VARCHAR(32) COMMENT '更新人',
    UPDATED_AT DATETIME COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '部门岗位表';

DROP TABLE IF EXISTS SYS_TENANT_PACKAGE;

CREATE TABLE SYS_TENANT_PACKAGE
(
    ID         VARCHAR(32) NOT NULL COMMENT 'ID',
    TENANT_ID  VARCHAR(32) COMMENT '租户ID',
    PACKAGE_ID VARCHAR(32) COMMENT '套餐ID',
    STATUS     INT COMMENT '数据状态（0正常 1停用）',
    DELETED    INT COMMENT '是否删除（0正常 1删除）',
    REVISION   VARCHAR(32) COMMENT '乐观锁',
    CREATED_BY VARCHAR(32) COMMENT '创建人',
    CREATED_AT DATETIME COMMENT '创建时间',
    UPDATED_BY VARCHAR(32) COMMENT '更新人',
    UPDATED_AT DATETIME COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '租户套餐表';